spring.application.name=lms

server.port=8080
 
# ===============================
# DATABASE - POSTGRESQL
# (Equivalent of SQLALCHEMY_DATABASE_URL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/lmsdb
spring.datasource.username=postgres
spring.datasource.password=Jyothin@2026
spring.datasource.driver-class-name=org.postgresql.Driver
 
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
 
# ===============================
# OPTIONAL (GOOD PRACTICE)
# ===============================
spring.jpa.open-in-view=false
spring.jackson.serialization.write-dates-as-timestamps=false
